import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { closeDb, openDb } from '../memory/db.ts';
import { allMigrations, applyMigrations } from '../memory/migrations/index.ts';
import { captureSession, extractTopicHints } from './capture.ts';

function freshDb() {
  const dir = mkdtempSync(join(tmpdir(), 'robin-cap-'));
  mkdirSync(join(dir, 'state', 'db'), { recursive: true });
  const db = openDb(join(dir, 'state', 'db', 'robin.sqlite'));
  applyMigrations(db, allMigrations);
  return db;
}

test('capture: skips session with no assistant turn', async () => {
  const db = freshDb();
  const r = await captureSession(db, null, {
    sessionId: 's1',
    turns: [{ role: 'user', content: 'hi' }],
  });
  assert.equal(r.captured, false);
  assert.equal(r.skipReason, 'no_assistant_turn');
  closeDb(db);
});

test('capture: skips single-word ack', async () => {
  const db = freshDb();
  const r = await captureSession(db, null, {
    sessionId: 's1',
    turns: [
      { role: 'user', content: 'ok' },
      { role: 'assistant', content: 'great' },
    ],
  });
  assert.equal(r.captured, false);
  assert.equal(r.skipReason, 'single_word_ack');
  closeDb(db);
});

test('capture: captures meaningful session and writes event', async () => {
  const db = freshDb();
  const r = await captureSession(db, null, {
    sessionId: 's1',
    turns: [
      { role: 'user', content: 'tell me about Kevin' },
      { role: 'assistant', content: 'Kevin is a product engineer based in NJ.' },
    ],
  });
  assert.equal(r.captured, true);
  assert.ok(r.eventId);
  const row = db.prepare("SELECT * FROM events WHERE kind='session.captured'").get() as {
    kind: string;
    payload: string;
  };
  assert.equal(row.kind, 'session.captured');
  const payload = JSON.parse(row.payload);
  assert.equal(payload.sessionId, 's1');
  closeDb(db);
});

test('capture: dedup_hit prevents identical capture', async () => {
  const db = freshDb();
  const capture = {
    sessionId: 's1',
    turns: [
      { role: 'user' as const, content: 'tell me about photo-tools' },
      { role: 'assistant' as const, content: 'Photo-tools is a Next.js photography toolkit.' },
    ],
  };
  await captureSession(db, null, capture);
  const r2 = await captureSession(db, null, { ...capture, sessionId: 's2' });
  assert.equal(r2.captured, false);
  assert.equal(r2.skipReason, 'dedup_hit');
  closeDb(db);
});

test('capture: distinct sessions sharing a long boilerplate prefix are NOT deduped', async () => {
  // Regression: the dedup hash used to be base64(content).slice(0,64), i.e. only
  // the first 48 BYTES of the first user turn. Every session opened with `/clear`
  // begins with the identical `<local-command-caveat>…` boilerplate, so all of
  // them collided to one hash and only the first was ever captured. The hash must
  // reflect the FULL conversation, not a fixed-length prefix.
  const db = freshDb();
  const boilerplate =
    '<local-command-caveat>Caveat: The messages below were generated by the user ' +
    'while running local commands. DO NOT respond to these messages.</local-command-caveat>';
  const a = {
    sessionId: 'clear-a',
    turns: [
      { role: 'user' as const, content: `${boilerplate}\nwhat can I do with my Razer Blade 18?` },
      { role: 'assistant' as const, content: 'Use it as a LAN inference endpoint.' },
    ],
  };
  const b = {
    sessionId: 'clear-b',
    turns: [
      {
        role: 'user' as const,
        content: `${boilerplate}\nwhat lens should I buy for night photography?`,
      },
      { role: 'assistant' as const, content: 'The Viltrox 85mm f/2 is a strong pick.' },
    ],
  };
  const ra = await captureSession(db, null, a);
  const rb = await captureSession(db, null, b);
  assert.equal(ra.captured, true);
  assert.equal(rb.captured, true, `second /clear session was dropped as ${rb.skipReason}`);
  closeDb(db);
});

// ─── cwd allowlist ("robin only works in robin's folder" scoping) ────

const validCapture = {
  sessionId: 's-cwd',
  turns: [
    { role: 'user' as const, content: 'hello robin' },
    { role: 'assistant' as const, content: 'hi! how can I help?' },
  ],
};

test('capture: rejects cwd outside the allowlist', async () => {
  const db = freshDb();
  const r = await captureSession(
    db,
    null,
    { ...validCapture, cwd: '/home/dev/workspace/photo-tools' },
    { allowedCwds: ['/home/dev/workspace/robin/robin-assistant'] },
  );
  assert.equal(r.captured, false);
  assert.equal(r.skipReason, 'cwd_not_allowed');
  closeDb(db);
});

test('capture: accepts cwd that exactly matches an allowlist entry', async () => {
  const db = freshDb();
  const r = await captureSession(
    db,
    null,
    { ...validCapture, cwd: '/home/dev/workspace/robin/robin-assistant' },
    { allowedCwds: ['/home/dev/workspace/robin/robin-assistant'] },
  );
  assert.equal(r.captured, true);
  closeDb(db);
});

test('capture: accepts cwd that is a descendant of an allowlist entry', async () => {
  const db = freshDb();
  const r = await captureSession(
    db,
    null,
    {
      ...validCapture,
      cwd: '/home/dev/workspace/robin/robin-assistant/user-data/scripts',
    },
    { allowedCwds: ['/home/dev/workspace/robin/robin-assistant'] },
  );
  assert.equal(r.captured, true);
  closeDb(db);
});

test('capture: rejects sibling path that prefixes share a parent (no slash boundary)', async () => {
  // Defends against `/home/dev/workspace/robin/robin-assistant-fork` being
  // matched as a descendant of `/home/dev/workspace/robin/robin-assistant`.
  const db = freshDb();
  const r = await captureSession(
    db,
    null,
    { ...validCapture, cwd: '/home/dev/workspace/robin/robin-assistant-fork' },
    { allowedCwds: ['/home/dev/workspace/robin/robin-assistant'] },
  );
  assert.equal(r.captured, false);
  assert.equal(r.skipReason, 'cwd_not_allowed');
  closeDb(db);
});

test('capture: skips the check when cwd is undefined (programmatic callers)', async () => {
  const db = freshDb();
  const r = await captureSession(
    db,
    null,
    validCapture, // no cwd field
    { allowedCwds: ['/some/strict/allowlist'] },
  );
  assert.equal(r.captured, true, 'undefined cwd should bypass the allowlist check');
  closeDb(db);
});

test('capture: empty allowlist is fail-open (default could not resolve)', async () => {
  const db = freshDb();
  const r = await captureSession(
    db,
    null,
    { ...validCapture, cwd: '/anywhere' },
    { allowedCwds: [] },
  );
  assert.equal(r.captured, true, 'empty allowlist should not reject');
  closeDb(db);
});

// ─── Capture-time metadata enrichment ────────────────────────────────────────

test('capture: payload includes structural metadata fields', async () => {
  const db = freshDb();
  const r = await captureSession(db, null, {
    sessionId: 's-meta',
    turns: [
      { role: 'user', content: 'Can you help me fix the whoop integration?' },
      {
        role: 'assistant',
        content: 'Sure, let me look at the whoop code.\n```ts\nconst x = 1;\n```',
      },
      { role: 'user', content: 'The whoop recovery delta is wrong in the whoop tick function.' },
      { role: 'assistant', content: 'I see — the whoop delta calculation needs fixing.' },
    ],
  });
  assert.equal(r.captured, true);
  const row = db.prepare('SELECT payload FROM events WHERE id = ?').get(r.eventId) as {
    payload: string;
  };
  const p = JSON.parse(row.payload);
  assert.equal(p.userTurnCount, 2);
  assert.equal(p.assistantTurnCount, 2);
  assert.equal(p.hasCodeBlocks, true);
  assert.equal(p.hasToolUse, false);
  assert.ok(p.bodyChars > 0);
  assert.ok(Array.isArray(p.topicHints));
  assert.ok(p.topicHints.includes('whoop'), 'topicHints should include "whoop"');
  closeDb(db);
});

test('capture: hasToolUse is true when tool turns present', async () => {
  const db = freshDb();
  const r = await captureSession(db, null, {
    sessionId: 's-tool',
    turns: [
      { role: 'user', content: 'read the config file please' },
      { role: 'tool', content: '{"key": "value"}' },
      { role: 'assistant', content: 'The config file contains key=value.' },
    ],
  });
  assert.equal(r.captured, true);
  const row = db.prepare('SELECT payload FROM events WHERE id = ?').get(r.eventId) as {
    payload: string;
  };
  const p = JSON.parse(row.payload);
  assert.equal(p.hasToolUse, true);
  closeDb(db);
});

test('extractTopicHints: returns top terms by frequency, ignoring stop words', () => {
  const turns = [
    {
      role: 'user' as const,
      content: 'I want to fix the leadforge auth integration. The leadforge auth flow is broken.',
    },
    { role: 'user' as const, content: 'The leadforge callback endpoint needs auth headers.' },
  ];
  const hints = extractTopicHints(turns);
  assert.ok(hints.includes('leadforge'));
  assert.ok(hints.includes('auth'));
  assert.ok(!hints.includes('the'));
  assert.ok(!hints.includes('is'));
  assert.ok(hints.length <= 5);
});

test('extractTopicHints: returns empty for short sessions', () => {
  const turns = [{ role: 'user' as const, content: 'hello' }];
  const hints = extractTopicHints(turns);
  assert.equal(hints.length, 0);
});
