// store.js — the only writer to events/memos/entities/edges/embeddings.
//
// Spec §5.1. All capture, biographer, dream, ingest, and outbound paths go
// through these primitives. Faculty lenses (knowledge.js, habits.js, …) are
// thin re-exports that bake `kind` in.
//
// Design rules baked in here:
//   1. Embeddings live in separable per-(profile, surface) tables. The store
//      writes the data row and the embedding row in the same transaction.
//   2. Edges use composite-ID UPSERT for idempotence; counter kinds use the
//      `SET field += 1` idiom verified against SurrealDB v3.0.5 (G0.b).
//   3. Content-hash dedupe is opt-in per kind via MEMO_KIND_REGISTRY[kind].dedup_by.
//   4. Subjects + lineage on memos are written as `about` / `derived_from` edges,
//      not as array fields on the memo row. (Spec §5.0 — fields removed.)
//   5. Validation happens via MEMO_KIND_REGISTRY / EDGE_KIND_REGISTRY before
//      any DB write; failures throw with a structured error message.

import { BoundQuery, surql } from 'surrealdb';
import { toRecordRef } from '../../data/db/record-ref.js';
import { sha256 } from '../../data/embed/hash.js';
import { activeProfile, embeddingTable } from '../../data/embed/profile-router.js';
import {
  canonicalEndpoints,
  EDGE_KIND_REGISTRY,
  isCounterKind,
  recordIdFromString,
  recordStringId,
  validateEdge,
} from './edge-registry.js';
import { MEMO_KIND_REGISTRY, validateAttachment, validateMemoKind } from './kind-registry.js';
import { persistentScopesSqlFilter, validateScope } from './scope-registry.js';
import { awaitTxBackoff, isTxConflict, withTxRetry } from './tx.js';

const PERSISTENT_SCOPES_FILTER = persistentScopesSqlFilter();

// ============================================================================
// WRITE PRIMITIVES
// ============================================================================

/**
 * Capture a raw event into the events firehose.
 *
 * Writes events row + embedding row (in the active profile's events surface)
 * in two queries — one transaction not strictly required because embedding
 * dedupe is keyed on event ID, which is generated by SurrealDB on insert.
 *
 * @returns {{ id, deduped: boolean }}
 */
export async function remember(db, embedder, input) {
  const {
    source,
    content,
    trust = 'trusted',
    scope = 'global',
    tags = [],
    attachments = [],
    meta,
    external_id,
  } = input;
  if (!source) throw new Error('remember: source required');
  if (!content || content.length === 0) throw new Error('remember: content required');
  validateScope(scope);

  // Validate attachments (open enum, but known kinds get their shape checked).
  for (const a of attachments) {
    const v = validateAttachment(a);
    if (!v.ok) throw new Error(`remember: attachment invalid: ${v.errors.join('; ')}`);
  }

  const contentHash = sha256(content);

  // Dedupe by content_hash within source — keeps integration syncs idempotent.
  const [existing] = await db
    .query(
      surql`SELECT id FROM events WHERE content_hash = ${contentHash} AND source = ${source} LIMIT 1`,
    )
    .collect();
  if (existing[0]) return { id: existing[0].id, deduped: true };

  // Normalize top-level `external_id` (sync convenience) into meta.external_id
  // — the events schema dropped the top-level column in the redesign.
  const normalizedMeta = external_id != null ? { ...(meta ?? {}), external_id } : meta;

  const fields = {
    source,
    content,
    content_hash: contentHash,
    trust,
    scope,
    tags,
    attachments,
    ...(normalizedMeta ? { meta: normalizedMeta } : {}),
  };
  const [created] = await db.query(surql`CREATE events CONTENT ${fields}`).collect();
  const row = Array.isArray(created) ? created[0] : created;
  const eventId = row.id;

  // Embedding failure must not lose the event. Mirrors recordEvent.
  try {
    await writeEmbedding(db, embedder, 'events', eventId, content);
  } catch (e) {
    console.warn(`store.remember: embedding failed for ${eventId}: ${e.message}`);
  }

  return { id: eventId, deduped: false };
}

/**
 * Create a memo of any kind. Subjects → `about` edges, lineage → `derived_from`
 * edges, both written via relateAll in the same call site.
 *
 * @returns {{ id, deduped: boolean }}
 */
export async function note(db, embedder, kind, input) {
  if (!kind) throw new Error('note: kind required');
  const v = validateMemoKind(kind, input);
  if (!v.ok) throw new Error(`note(${kind}): ${v.errors.join('; ')}`);
  const {
    content,
    subjects = [],
    confidence,
    scope = 'global',
    tags = [],
    derived_by,
    lineage = [],
    meta = {},
    derived_from_trust,
  } = input;

  validateScope(scope);
  const spec = MEMO_KIND_REGISTRY[kind];
  const dedupByHash = spec?.dedup_by === 'content_hash';
  const contentHash = sha256(content);

  if (dedupByHash) {
    const [existing] = await db
      .query(
        surql`SELECT id FROM memos WHERE kind = ${kind} AND content_hash = ${contentHash} LIMIT 1`,
      )
      .collect();
    if (existing[0]) return { id: existing[0].id, deduped: true };
  }

  const fields = {
    kind,
    content,
    content_hash: contentHash,
    derived_by,
    scope,
    tags,
    meta,
    ...(confidence !== undefined ? { confidence } : {}),
    ...(derived_from_trust != null ? { derived_from_trust } : {}),
  };
  const [created] = await db.query(surql`CREATE memos CONTENT ${fields}`).collect();
  const row = Array.isArray(created) ? created[0] : created;
  const memoId = row.id;

  // Embedding failure must not lose the memo. Mirrors recordEvent: the memo
  // row is already created above; if the embedder is mis-configured or
  // produces a vector the active table's schema rejects (e.g. mock 1024-d
  // vector vs gemini-3072 profile), log a warning and continue. Recall by
  // semantic search will be degraded until the row is back-filled, but
  // writes don't bubble InternalError to MCP clients.
  try {
    await writeEmbedding(db, embedder, 'memos', memoId, content);
  } catch (e) {
    console.warn(`store.note: embedding failed for ${memoId}: ${e.message}`);
  }

  // Emit `about` edges for subjects (memo → entity).
  if (subjects.length > 0) {
    const rows = subjects.map((s) => ({ from: memoId, to: s, kind: 'about' }));
    await relateAll(db, rows);
  }
  // Emit `derived_from` edges for lineage entries.
  if (lineage.length > 0) {
    const rows = lineage.map((l) => ({ from: memoId, to: l.id ?? l, kind: 'derived_from' }));
    await relateAll(db, rows);
  }

  return { id: memoId, deduped: false };
}

/**
 * Upsert a memo by its `meta.name`. Used by habits today; the primitive is
 * generic (any kind that carries `meta.name`). Increments `signal_count` and
 * refreshes `last_active` on match; creates otherwise.
 *
 * @returns {{ id, signal_increment: 0 | 1 }}
 */
export async function upsertMemoByName(db, embedder, kind, input) {
  const { name } = input;
  if (!name) throw new Error('upsertMemoByName: meta.name required (passed as input.name)');
  // SELECT-then-CREATE is not strictly atomic. Wrap in withTxRetry so the
  // SurrealDB engine's "Transaction conflict" surface for paired callers is
  // retried with jittered backoff; concurrent callers converge to one row.
  return withTxRetry(async () => {
    const [existing] = await db
      .query(surql`SELECT id FROM memos WHERE kind = ${kind} AND meta.name = ${name} LIMIT 1`)
      .collect();
    if (existing[0]) {
      const id = toRecordRef(existing[0].id);
      await db
        .query(surql`UPDATE ${id} SET signal_count += 1, last_active = time::now()`)
        .collect();
      // Also merge any new lineage as derived_from edges.
      if (input.lineage?.length > 0) {
        const rows = input.lineage.map((l) => ({
          from: id,
          to: l.id ?? l,
          kind: 'derived_from',
        }));
        await relateAll(db, rows);
      }
      return { id, signal_increment: 1 };
    }
    // Create path: ensure `meta.name` is part of the meta we pass through.
    const meta = { ...(input.meta ?? {}), name };
    const result = await note(db, embedder, kind, { ...input, meta });
    return { id: result.id, signal_increment: 0 };
  });
}

/**
 * Relate two records with a typed edge. Registry-validated. Self-loops
 * rejected. Symmetric kinds canonicalize endpoint order. Composite-ID UPSERT
 * for idempotence; counter kinds use `SET weight += 1`.
 */
export async function relate(db, from, to, kind, opts = {}) {
  const v = validateEdge(from, to, kind);
  if (!v.ok) throw new Error(`relate: ${v.errors.join('; ')}`);
  const [cFrom, cTo] = canonicalEndpoints(from, to, kind);
  const counter = isCounterKind(kind);

  // Build a deterministic composite ID. SurrealDB v3 accepts record-as-id-element
  // via the array literal syntax — we use BoundQuery here so the parser sees
  // literal record refs in the ID position.
  const fromIdStr = recordStringId(cFrom);
  const toIdStr = recordStringId(cTo);

  // Coerce strings to RecordId before binding — see comment in relateAll.
  const inRec = recordIdFromString(cFrom);
  const outRec = recordIdFromString(cTo);

  if (counter) {
    // TYPE RELATION tables don't accept UPSERT/CREATE for new rows; use
    // INSERT RELATION ... ON DUPLICATE KEY UPDATE for idempotent counter
    // increments. Bind params are $inRec/$outRec to avoid $in/$out clashing
    // with SurrealQL field-name parsing.
    const sql = `INSERT RELATION INTO edges {
      id: [$kind, $inRec, $outRec],
      in: $inRec, out: $outRec, kind: $kind, weight: 1, last_seen: time::now()
    } ON DUPLICATE KEY UPDATE
      weight += 1, last_seen = time::now()`;
    const [ret] = await db
      .query(
        new BoundQuery(sql, {
          kind,
          inRec,
          outRec,
        }),
      )
      .collect();
    const row = Array.isArray(ret) ? ret[0] : ret;
    return { id: row?.id };
  }

  const bindings = { kind, inRec, outRec };
  // Build the insert-content map and the on-duplicate update set in parallel,
  // so optional fields like weight/valid_from/etc. apply on both code paths.
  const insertFields = [
    'id: [$kind, $inRec, $outRec]',
    'in: $inRec',
    'out: $outRec',
    'kind: $kind',
    'last_seen: time::now()',
  ];
  const updateExprs = ['kind = $kind', 'last_seen = time::now()'];
  for (const [field, val] of [
    ['weight', opts.weight],
    ['valid_from', opts.valid_from],
    ['valid_until', opts.valid_until],
    ['context', opts.context],
    ['meta', opts.meta],
    ['derived_from_trust', opts.derived_from_trust],
  ]) {
    if (val !== undefined && val !== null) {
      bindings[field] = val;
      insertFields.push(`${field}: $${field}`);
      updateExprs.push(`${field} = $${field}`);
    }
  }
  const sql = `INSERT RELATION INTO edges { ${insertFields.join(', ')} }
    ON DUPLICATE KEY UPDATE ${updateExprs.join(', ')}`;
  const [ret] = await db.query(new BoundQuery(sql, bindings)).collect();
  const row = Array.isArray(ret) ? ret[0] : ret;

  return { id: row?.id, fromId: fromIdStr, toId: toIdStr };
}

/**
 * Bulk relate. Builds one multi-statement query so a 20-edge biographer fan-out
 * costs 1 round-trip instead of 20. Chunks at 50 to avoid pathological parser
 * limits. Wrapped in BEGIN/COMMIT so a malformed edge doesn't leave partial state.
 */
const RELATE_CHUNK = 50;
// Per-slice transaction-conflict retry. Keeps a smaller cap than the outer
// withTxRetry (4) because relateAll is hot-path and slices are independent —
// 2 retries with jittered backoff resolves the common race-on-same-edge case
// without amplifying latency on terminal errors.
const TX_CONFLICT_MAX_RETRIES = 2;
export async function relateAll(db, rows) {
  if (!Array.isArray(rows) || rows.length === 0) return { ids: [] };
  // Pre-filter invalid edges (self-loops, unknown kinds, wrong endpoint tables)
  // and log each skip. The biographer pipeline routinely produces small batches
  // that include 1-2 redundant self-loops (LLM aliasing two synonymous names to
  // the same canonical entity); failing the whole batch on a single invalid
  // edge means we silently drop *all* of the surrounding good edges for the
  // event — a much worse outcome than just dropping the bad ones.
  const valid = [];
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const v = validateEdge(row.from, row.to, row.kind);
    if (!v.ok) {
      console.warn(`relateAll[${i}]: skipping invalid edge — ${v.errors.join('; ')}`);
      continue;
    }
    valid.push(row);
  }
  if (valid.length === 0) return { ids: [] };
  const ids = [];
  for (let off = 0; off < valid.length; off += RELATE_CHUNK) {
    const slice = valid.slice(off, off + RELATE_CHUNK);
    const stmts = ['BEGIN TRANSACTION'];
    const bindings = {};
    slice.forEach((row, i) => {
      const [cIn, cOut] = canonicalEndpoints(row.from, row.to, row.kind);
      bindings[`k${i}`] = row.kind;
      // SurrealDB's `INSERT RELATION INTO edges { in: $i, out: $o }` requires
      // `in` / `out` to bind as Thing (RecordId) values, not plain strings.
      // A string binding ("entities:foo") triggers
      //   "Cannot execute INSERT statement where property 'in' is: 'entities:foo'"
      // — and because each slice runs inside one BEGIN/COMMIT, the failure
      // cascades into "query was not executed due to a failed transaction"
      // for every following row, dropping the entire 50-edge chunk.
      // `recordIdFromString` is a pass-through for non-strings, so safe to
      // apply unconditionally regardless of which caller (biographer,
      // ingest, v1-import) produced the row.
      bindings[`i${i}`] = recordIdFromString(cIn);
      bindings[`o${i}`] = recordIdFromString(cOut);
      const insertFields = [
        `id: [$k${i}, $i${i}, $o${i}]`,
        `in: $i${i}`,
        `out: $o${i}`,
        `kind: $k${i}`,
        `last_seen: time::now()`,
      ];
      const updateExprs = [`kind = $k${i}`, `last_seen = time::now()`];
      if (isCounterKind(row.kind)) {
        insertFields.push(`weight: 1`);
        updateExprs.push(`weight += 1`);
      } else {
        for (const f of [
          'weight',
          'valid_from',
          'valid_until',
          'context',
          'meta',
          'derived_from_trust',
        ]) {
          if (row[f] != null) {
            bindings[`${f}${i}`] = row[f];
            insertFields.push(`${f}: $${f}${i}`);
            updateExprs.push(`${f} = $${f}${i}`);
          }
        }
      }
      stmts.push(
        `INSERT RELATION INTO edges { ${insertFields.join(', ')} } ON DUPLICATE KEY UPDATE ${updateExprs.join(', ')}`,
      );
    });
    stmts.push('COMMIT TRANSACTION');
    // Per-slice try/catch: a transaction reject on one slice (e.g. SurrealDB
    // refusing a RecordId with special chars in the bound `out` field) used
    // to bubble up and kill the entire relateAll batch, dropping every other
    // valid edge. Each slice has its own BEGIN/COMMIT, so a failure here is
    // already atomically scoped to just this 50-edge chunk.
    //
    // Transaction conflicts (concurrent writer racing the same edge) are
    // retryable — fail-and-skip would drop ~25 edges per conflict, and they
    // recur under sustained sync load. Retry transient conflicts a few times
    // with jittered backoff before giving up; non-conflict errors (parser /
    // schema reject) skip the slice immediately as before.
    let sliceErr = null;
    for (let attempt = 0; attempt <= TX_CONFLICT_MAX_RETRIES; attempt++) {
      try {
        const results = await db.query(new BoundQuery(stmts.join(';\n'), bindings)).collect();
        for (const r of results) {
          const row = Array.isArray(r) ? r[0] : r;
          if (row?.id) ids.push(row.id);
        }
        sliceErr = null;
        break;
      } catch (e) {
        sliceErr = e;
        if (!isTxConflict(e)) break;
        await awaitTxBackoff();
      }
    }
    if (sliceErr) {
      const suffix = isTxConflict(sliceErr) ? ' (retried, still conflict)' : '';
      console.warn(
        `relateAll: slice [${off}..${off + slice.length - 1}] failed, skipping ${slice.length} edges${suffix}: ${sliceErr.message}`,
      );
    }
  }
  return { ids };
}

/**
 * Add a `supersedes` edge new_memo → old_memo. fn::freshness will return 0
 * for old_memo from now on (per its inbound supersedes check). The old memo
 * row is NOT updated/deleted — historical readings remain queryable.
 */
export async function supersede(db, oldId, newId) {
  const { id } = await relate(db, newId, oldId, 'supersedes');
  return { superseded: oldId, by: newId, edge: id };
}

/**
 * Mark two memos as contradicting each other (symmetric, both visible).
 */
export async function flagContradiction(db, idA, idB, opts = {}) {
  return relate(db, idA, idB, 'contradicts', opts);
}

/**
 * Update a memo's `meta` field by merging in a patch. Used by foresight to
 * record prediction resolution (resolved_at / correct / actual_outcome).
 */
export async function updateMemoMeta(db, id, patch) {
  await db.query(surql`UPDATE ${toRecordRef(id)} MERGE { meta: ${patch} }`).collect();
}

// ============================================================================
// EMBEDDINGS
// ============================================================================

/**
 * Write the embedding for a record into the active profile's embedding table
 * for the given surface. Idempotent (UPSERT by the record's ID).
 *
 * Profile name is read from `runtime:embedder.active_profile` and validated
 * against /^[a-z0-9-]+$/ in profile-router; surface against /^events|memos|entities$/.
 * Table name is therefore safe to interpolate.
 */
async function writeEmbedding(db, embedder, surface, recordId, text) {
  const profile = await activeProfile(db);
  const table = embeddingTable(profile, surface);
  const vec = Array.from(await embedder.embed(text));
  const sql = 'UPSERT type::record($tb, [$rec]) SET record = $rec, vector = $vec, ts = time::now()';
  await db
    .query(
      new BoundQuery(sql, {
        tb: table,
        rec: recordId,
        vec,
      }),
    )
    .collect();
}

// ============================================================================
// READ PRIMITIVES
// ============================================================================

/**
 * HNSW kNN over memos. Filters by kind / scope(s) / tags / since are applied
 * during the SQL query (indexed where applicable). Default excludes ephemeral
 * scopes; pass `scopes: ['*']` to include everything.
 *
 * Returns `{ hits: [{ record, distance, ... }] }` — caller layers rank.score.
 */
export async function searchMemos(db, embedder, query, opts = {}) {
  return _surfaceSearch(db, embedder, 'memos', query, opts);
}

export async function searchEvents(db, embedder, query, opts = {}) {
  return _surfaceSearch(db, embedder, 'events', query, opts);
}

// Hybrid retrieval (Phase 4 — section 2 of the surrealdb-improvements spec)
// runs vector + BM25 in parallel and fuses with RRF. Adaptive over-fetch on
// the kNN side mitigates post-filter shrinkage when callers narrow by
// kind/scope/tags/since.

/**
 * Build a SurrealQL WHERE fragment for the memo `kind` filter.
 *
 * Accepts string OR array. Pushes the value into `bindings.kind` and returns
 * the WHERE fragment for callers to push into `filters`.
 *
 * Shared by `_surfaceSearch` (post-filter SELECT after kNN+BM25 fusion) and
 * `listMemos` (chronological list). The two were the only sites in this file
 * that filtered memos by `kind`; both must accept array-kind for the public
 * API contract to hold. (Cognition D2 spec §5.)
 */
function kindFilter(kind, bindings) {
  bindings.kind = kind;
  return Array.isArray(kind) ? 'kind IN $kind' : 'kind = $kind';
}

const HYBRID_DEFAULTS = {
  // Legacy hybrid-recall tunables (0001-init seed).
  rrf_k: 60,
  knn_overfetch_base: 1.5,
  knn_overfetch_per_filter: 1.5,
  mmr_threshold: 0.92,
  // B2 conflict-surfacing tunables (0015 seed). Defaults match the seed so
  // partial config rows (e.g., dev installs that didn't run 0015 yet) still
  // resolve to a working shape.
  conflict_surfacing_enabled: false,
  conflict_min_confidence: 0.4,
  conflict_max_age_days: 30,
  conflict_max_pairs_surfaced: 3,
  conflict_max_pairs_hydrated: 24,
  conflict_block_token_budget: 300,
  relevant_memory_token_budget: 1500,
};

let _recallConfigCache = null;
let _recallConfigCachedAt = 0;

/**
 * Reset the recall-config cache. For tests that need to bust the 5-s TTL
 * (e.g., after toggling `runtime:recall.value.conflict_surfacing_enabled`
 * or `runtime:recall.value.entity_boost_enabled` mid-suite). Production
 * callers should never need this. Exported under both names for test
 * compatibility across rounds.
 */
export function _resetRecallConfigCache() {
  _recallConfigCache = null;
  _recallConfigCachedAt = 0;
}
export const __resetRecallConfigCacheForTests = _resetRecallConfigCache;

export async function getRecallConfig(db) {
  // 5-second cache; runtime:recall is read on every search call.
  if (_recallConfigCache && Date.now() - _recallConfigCachedAt < 5000) {
    return _recallConfigCache;
  }
  try {
    // SurrealDB v3 treats both `runtime` (the table name) and `value`
    // (the column name) as parse-sensitive: `runtime` because the
    // schema-level keyword shadows it in certain contexts, `value` because
    // it's reserved in projection lists. Use the raw-record syntax for
    // the FROM target and `SELECT VALUE value` to project the column
    // directly. The original `'SELECT value FROM runtime:recall'` was
    // silently throwing, masking config drift behind HYBRID_DEFAULTS.
    const [rows] = await db.query('SELECT VALUE value FROM r"runtime:recall"').collect();
    const value = rows?.[0] ?? {};
    _recallConfigCache = { ...HYBRID_DEFAULTS, ...value };
  } catch {
    _recallConfigCache = HYBRID_DEFAULTS;
  }
  _recallConfigCachedAt = Date.now();
  return _recallConfigCache;
}

function countActiveFilters(opts, surface) {
  let n = 0;
  if (surface === 'memos' && opts.kind) n += 1;
  if (surface === 'events' && opts.source) n += 1;
  if (surface === 'entities' && opts.type) n += 1;
  if (Array.isArray(opts.scopes) && !opts.scopes.includes('*')) n += 1;
  if (opts.tags && opts.tags.length > 0) n += 1;
  if (opts.since) n += 1;
  return n;
}

async function _surfaceSearch(db, embedder, surface, query, opts) {
  const limit = Number.isInteger(opts.limit) ? opts.limit : 10;
  if (limit < 1 || limit > 100) {
    throw new Error(`searchMemos: limit out of range [1,100]: ${limit}`);
  }

  // Hybrid retrieval can be disabled per-call (e.g. for explainability tests)
  // via opts.disableBm25 — vector-only path remains the legacy semantics.
  const cfg = await getRecallConfig(db);
  const filterCount = countActiveFilters(opts, surface);
  const knnK = Math.min(
    100,
    Math.max(
      limit,
      Math.ceil(limit * (cfg.knn_overfetch_base + filterCount * cfg.knn_overfetch_per_filter)),
    ),
  );
  const ef = Math.max(64, knnK * 4);
  const { readProfile } = await import('../../data/embed/profile-router.js');
  const readProf = await readProfile(db);
  const embeddingTbl = embeddingTable(readProf, surface);
  const qvec = Array.from(await embedder.embed(query));

  // Step 1: HNSW kNN on the per-surface embeddings table.
  // TIMEOUT 2s is defensive — bounds runaway HNSW exploration if the index
  // is in a pathological state. Recall is fail-soft from the hook side, so
  // a timeout produces an empty hit list rather than crashing the turn.
  const knnSql = `SELECT record, vector::distance::knn() AS dist
                  FROM ${embeddingTbl}
                  WHERE vector <|${knnK}, ${ef}|> $qvec
                  ORDER BY dist
                  LIMIT ${knnK}
                  TIMEOUT 2s`;
  const [knnRows] = await db.query(new BoundQuery(knnSql, { qvec })).collect();

  // Step 1b (Phase 4): BM25 keyword retrieval. Fail-soft — FULLTEXT indexes
  // were added in Phase 1 but if the engine version doesn't support the
  // index variant, vector-only recall still works.
  let bm25Rows = [];
  if (!opts.disableBm25 && query && query.length > 0) {
    bm25Rows = await _bm25Retrieve(db, surface, query, knnK).catch(() => []);
  }

  if (knnRows.length === 0 && bm25Rows.length === 0) return { hits: [] };

  // Step 2: fetch records and apply scope/kind/tags filter.
  // We hydrate the union of kNN and BM25 candidates in a single SELECT.
  const idDist = new Map(knnRows.map((r) => [recordStringId(r.record), r.dist]));
  const candidateIdSet = new Set();
  const ids = [];
  for (const r of knnRows) {
    const k = recordStringId(r.record);
    if (!candidateIdSet.has(k)) {
      candidateIdSet.add(k);
      ids.push(r.record);
    }
  }
  for (const r of bm25Rows) {
    const k = recordStringId(r.id);
    if (!candidateIdSet.has(k)) {
      candidateIdSet.add(k);
      ids.push(r.id);
    }
  }

  const filters = ['id IN $ids'];
  const bindings = { ids };
  if (surface === 'memos' && opts.kind) {
    filters.push(kindFilter(opts.kind, bindings));
  }
  if (surface === 'events' && opts.source) {
    bindings.source = opts.source;
    filters.push('source = $source');
  }
  if (surface === 'entities' && opts.type) {
    bindings.entitytype = opts.type;
    filters.push('type = $entitytype');
  }
  const scopes = opts.scopes;
  if (opts.scope_descends_from) {
    bindings.scope_root = opts.scope_descends_from;
    filters.push("(scope = $scope_root OR string::starts_with(scope, $scope_root + '/'))");
  } else if (scopes === undefined && !opts.includeEphemeral) {
    // default: exclude ephemerals (registry-derived)
    filters.push(PERSISTENT_SCOPES_FILTER);
  } else if (Array.isArray(scopes) && !scopes.includes('*')) {
    bindings.scopes = scopes;
    filters.push('scope IN $scopes');
  }
  if (opts.tags && opts.tags.length > 0) {
    bindings.tags = opts.tags;
    filters.push('tags CONTAINSANY $tags');
  }
  if (opts.since) {
    bindings.since = new Date(opts.since);
    const tsField = surface === 'events' ? 'ts' : 'derived_at';
    filters.push(`${tsField} >= $since`);
  }

  const fetchSql = `SELECT * FROM ${surface} WHERE ${filters.join(' AND ')}`;
  const [rows] = await db.query(new BoundQuery(fetchSql, bindings)).collect();

  // Phase 4: build kNN- and BM25-ranked lists from the hydrated rows, then
  // RRF-fuse them. BM25-only hits get distance=0.5 in fusion.padDistances.
  const { rrfFuse, padDistances } = await import('../intuition/fusion.js');
  const rowById = new Map(rows.map((r) => [recordStringId(r.id), r]));

  // kNN-ordered hydrated hits (only those that survived post-filters).
  const knnHits = [];
  for (const k of knnRows) {
    const key = recordStringId(k.record);
    const row = rowById.get(key);
    if (!row) continue;
    knnHits.push({ id: row.id, ...row, distance: k.dist, _source: 'knn' });
  }
  // BM25-ordered hydrated hits.
  const bm25Hits = [];
  for (const b of bm25Rows) {
    const key = recordStringId(b.id);
    const row = rowById.get(key);
    if (!row) continue;
    bm25Hits.push({ id: row.id, ...row, distance: undefined, _source: 'bm25' });
  }

  const fused = padDistances(rrfFuse([knnHits, bm25Hits], { k: cfg.rrf_k }));
  const final = fused.slice(0, limit);

  // Keep RRF order (do NOT re-sort by distance — that would undo the fusion).
  const hits = final.map((row) => ({
    record: row,
    distance: row.distance ?? idDist.get(recordStringId(row.id)) ?? 1,
    _sources: row._sources ?? [],
    _rrf: row._rrf ?? 0,
  }));

  return {
    hits,
    debug: { knn_n: knnHits.length, bm25_n: bm25Hits.length, fused_n: fused.length },
  };
}

/**
 * BM25 keyword retrieval helper. Fails-soft on missing FULLTEXT indexes so
 * vector-only recall keeps working on engines that don't support BM25.
 */
async function _bm25Retrieve(db, surface, query, k) {
  const indexName =
    surface === 'memos'
      ? 'memos_content_fts'
      : surface === 'events'
        ? 'events_content_fts'
        : surface === 'entities'
          ? 'entities_name_fts'
          : null;
  if (!indexName) return [];
  const field = surface === 'entities' ? 'name' : 'content';
  const sql = `SELECT id, search::score(0) AS bm25_score
               FROM ${surface} WITH INDEX ${indexName}
               WHERE ${field} @0@ $q
               ORDER BY bm25_score DESC
               LIMIT ${k}
               TIMEOUT 2s`;
  const [rows] = await db.query(new BoundQuery(sql, { q: query })).collect();
  return rows ?? [];
}

/**
 * Non-vector list (index-backed): used by lenses for chronological views.
 */
export async function listMemos(db, opts = {}) {
  const { kind, scope, since, until, limit = 50 } = opts;
  if (!Number.isInteger(limit) || limit < 1 || limit > 1000) {
    throw new Error(`listMemos: limit out of range [1,1000]: ${limit}`);
  }
  const filters = [];
  const bindings = {};
  if (kind) {
    filters.push(kindFilter(kind, bindings));
  }
  if (scope) {
    filters.push('scope = $scope');
    bindings.scope = scope;
  }
  if (since) {
    filters.push('derived_at >= $since');
    bindings.since = new Date(since);
  }
  if (until) {
    filters.push('derived_at <= $until');
    bindings.until = new Date(until);
  }
  const where = filters.length > 0 ? `WHERE ${filters.join(' AND ')}` : '';
  const sql = `SELECT * FROM memos ${where} ORDER BY last_active DESC LIMIT ${limit}`;
  const [rows] = await db.query(new BoundQuery(sql, bindings)).collect();
  return rows;
}

/**
 * Bidirectional neighbor lookup along an edge kind.
 * For symmetric kinds, returns the *other* endpoint regardless of direction.
 * For asymmetric kinds with `direction = 'out'` (default), returns `to`s of
 * outbound edges; `direction = 'in'` returns `from`s of inbound; `'both'`
 * returns the union.
 */
export async function neighbors(db, recordId, kind, opts = {}) {
  const { limit = 10, direction = 'out' } = opts;
  if (!Number.isInteger(limit) || limit < 1 || limit > 1000) {
    throw new Error(`neighbors: limit out of range [1,1000]: ${limit}`);
  }
  const spec = EDGE_KIND_REGISTRY[kind];
  if (!spec) throw new Error(`neighbors: unknown kind ${kind}`);
  let whereClause;
  if (spec.symmetric) {
    whereClause = '(in = $e OR out = $e)';
  } else if (direction === 'out') {
    whereClause = 'in = $e';
  } else if (direction === 'in') {
    whereClause = 'out = $e';
  } else {
    whereClause = '(in = $e OR out = $e)';
  }
  const sql = `SELECT
    IF in = $e THEN out ELSE in END AS other,
    weight, last_seen, valid_from, valid_until
    FROM edges
    WHERE kind = $k AND ${whereClause}
    ORDER BY weight DESC
    LIMIT ${limit}`;
  const [rows] = await db.query(new BoundQuery(sql, { e: recordId, k: kind })).collect();
  return rows;
}

// ============================================================================
// ENTITY UPSERT (delegates to existing 3-stage cascade for now)
// ============================================================================

/**
 * Upsert an entity by name (exact + embedding + LLM disambig cascade).
 * Current implementation delegates to the existing 3-stage cascade in
 * src/graph/stage*.js; this primitive exists so all writes route through
 * one module. The embedding write moves to the per-surface entities table.
 */
export async function upsertEntity(db, embedder, input) {
  if (input?.scope !== undefined) validateScope(input.scope);
  const { upsertEntityCascade } = await import('../biographer/upsert-entity.js');
  const result = await upsertEntityCascade(db, embedder, input);
  // Write embedding into the active profile's entities surface.
  // Mirrors recordEvent/note: entity row already exists (created in the
  // cascade); a dim-mismatch or embedder outage must not bubble.
  if (result.id && result.embedding_source) {
    try {
      await writeEmbedding(db, embedder, 'entities', result.id, result.embedding_source);
    } catch (e) {
      console.warn(`store.upsertEntity: embedding failed for ${result.id}: ${e.message}`);
    }
  }
  return result;
}
