// system/scripts/memory/lib/entity-index.js
//
// Read/write/incremental update of user-data/memory/ENTITIES.md.
// Edit-detection via content hash stored in user-data/runtime/state/cache/entities-hash.txt.

import { readFileSync, readdirSync, lstatSync, writeFileSync, existsSync, mkdirSync, renameSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { createHash } from 'node:crypto';

const ENTITIES_FILE = 'user-data/memory/ENTITIES.md';
const EXTENDED_FILE = 'user-data/memory/ENTITIES-extended.md';
const HASH_FILE = 'user-data/runtime/state/cache/entities-hash.txt';
const DO_NOT_EDIT_MARKER = '<!-- DO NOT EDIT — auto-generated by Dream Phase 4.17.6. Edit topic-file aliases instead. -->';

function ensureDir(file) {
  mkdirSync(dirname(file), { recursive: true });
}

function atomicWrite(file, content) {
  ensureDir(file);
  const tmp = `${file}.${process.pid}.${Date.now()}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, file);
}

function* walkMarkdown(dir) {
  if (!existsSync(dir)) return;
  for (const name of readdirSync(dir)) {
    if (name.startsWith('.') || name === 'ENTITIES.md' || name === 'ENTITIES-extended.md') continue;
    const full = join(dir, name);
    let st;
    try { st = lstatSync(full); } catch { continue; }
    // Skip symlinks: prevents memDir escape and cycle infinite-recursion.
    if (st.isSymbolicLink()) continue;
    if (st.isDirectory()) yield* walkMarkdown(full);
    else if (name.endsWith('.md')) yield full;
  }
}

function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) return null;
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^(\w+):\s*(.+)$/);
    if (kv) {
      let val = kv[2].trim();
      if (val.startsWith('[') && val.endsWith(']')) {
        val = val.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
      }
      fm[kv[1].trim()] = val;
    }
  }
  return fm;
}

function deriveName(file, fm) {
  if (fm?.description) {
    const dash = fm.description.indexOf(' — ');
    if (dash > 0) return fm.description.slice(0, dash).trim();
  }
  // fallback: filename stem prettified
  const stem = file.split('/').pop().replace(/\.md$/, '');
  return stem.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function collectEntities(workspaceDir) {
  const memDir = join(workspaceDir, 'user-data/memory');
  const out = [];
  for (const file of walkMarkdown(memDir)) {
    const text = readFileSync(file, 'utf8');
    const fm = parseFrontmatter(text);
    if (!fm) continue;
    const isEntity = fm.type === 'entity';
    const hasAliases = Array.isArray(fm.aliases) && fm.aliases.length > 0;
    if (!isEntity && !hasAliases) continue;

    // Derive name: prefer first H1 heading, then description, then filename stem
    let name;
    const h1 = text.match(/^# (.+)$/m);
    if (h1) {
      name = h1[1].trim();
    } else {
      name = deriveName(file, fm);
    }

    out.push({
      name,
      aliases: Array.isArray(fm.aliases) ? fm.aliases : [],
      disambiguator: Array.isArray(fm.disambiguator) ? fm.disambiguator : [],
      file: relative(memDir, file),
      section: null,
    });
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

export function renderEntitiesMarkdown(entities, opts = {}) {
  const generated = opts.generated ?? new Date().toISOString();
  const lines = [
    '---',
    'description: Auto-generated entity index for fast recall lookup',
    'type: reference',
    `generated: ${generated}`,
    '---',
    '# Entities',
    '',
    DO_NOT_EDIT_MARKER,
    '',
  ];
  for (const e of entities) {
    const aliases = e.aliases.length ? ` (${e.aliases.join(', ')})` : '';
    const section = e.section ? `#${e.section.toLowerCase().replace(/\s+/g, '-')}` : '';
    lines.push(`- ${e.name}${aliases} — ${e.file}${section}`);
  }
  lines.push('');
  return lines.join('\n');
}

function hashContent(content) {
  return createHash('sha256').update(content).digest('hex');
}

export function writeEntitiesAtomic(workspaceDir, entities, opts = {}) {
  const hotCap = opts.hotCap ?? 150;
  const generated = opts.generated ?? new Date().toISOString();
  const hot = entities.slice(0, hotCap);
  const extended = entities.slice(hotCap);

  const hotMd = renderEntitiesMarkdown(hot, { generated });
  atomicWrite(join(workspaceDir, ENTITIES_FILE), hotMd);
  atomicWrite(join(workspaceDir, HASH_FILE), hashContent(hotMd));

  if (extended.length > 0) {
    const extMd = renderEntitiesMarkdown(extended, { generated });
    atomicWrite(join(workspaceDir, EXTENDED_FILE), extMd);
  }
}

export function readEntities(workspaceDir) {
  const file = join(workspaceDir, ENTITIES_FILE);
  if (!existsSync(file)) return { entities: [], extended: 0 };
  const text = readFileSync(file, 'utf8');
  const entities = [];
  for (const line of text.split('\n')) {
    const m = line.match(/^- (.+?)(?: \((.+?)\))? — (.+)$/);
    if (m) {
      entities.push({
        name: m[1],
        aliases: m[2] ? m[2].split(', ') : [],
        file: m[3].split('#')[0],
        section: m[3].split('#')[1] ?? null,
      });
    }
  }
  return { entities, extended: existsSync(join(workspaceDir, EXTENDED_FILE)) ? 1 : 0 };
}

export function detectUserEdit(workspaceDir) {
  const file = join(workspaceDir, ENTITIES_FILE);
  const hashFile = join(workspaceDir, HASH_FILE);
  if (!existsSync(file) || !existsSync(hashFile)) return false;
  const stored = readFileSync(hashFile, 'utf8').trim();
  const current = hashContent(readFileSync(file, 'utf8'));
  return stored !== current;
}
