import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import type { Invariant } from './types.ts';

const BEGIN = '<!-- robin:runbook:begin -->';
const END = '<!-- robin:runbook:end -->';

export function emitRunbookSection(invariants: Invariant[]): string {
  const lines: string[] = [];
  lines.push('## Operational invariants (auto-generated)');
  lines.push('');
  lines.push(
    '> This section is regenerated by `robin doctor --emit-runbook --write`. Do not edit between the sentinel comments.',
  );
  lines.push('');
  const grouped = new Map<string, Invariant[]>();
  for (const inv of invariants) {
    const ns = inv.name.includes('.') ? inv.name.split('.')[0] : 'general';
    if (!grouped.has(ns)) grouped.set(ns, []);
    grouped.get(ns)?.push(inv);
  }
  for (const [ns, list] of grouped) {
    lines.push(`### ${ns}`);
    lines.push('');
    for (const inv of list) {
      lines.push(`#### \`${inv.name}\` (${inv.severity})`);
      lines.push('');
      lines.push(`**Symptom.** ${inv.symptom}`);
      lines.push('');
      lines.push(`**Cause.** ${inv.cause}`);
      lines.push('');
      lines.push(`**Fix.** ${inv.fix}`);
      lines.push('');
    }
  }
  return lines.join('\n');
}

export function writeRunbook(path: string, invariants: Invariant[]): { existed: boolean } {
  const existed = existsSync(path);
  let body: string;
  if (existed) {
    const cur = readFileSync(path, 'utf8');
    const beginIdx = cur.indexOf(BEGIN);
    const endIdx = cur.indexOf(END);
    if (beginIdx !== -1 && endIdx !== -1) {
      const before = cur.slice(0, beginIdx + BEGIN.length);
      const after = cur.slice(endIdx);
      body = `${before}\n\n${emitRunbookSection(invariants)}\n\n${after}`;
    } else {
      // Append sentinel block at end
      body = `${cur}\n\n${BEGIN}\n\n${emitRunbookSection(invariants)}\n\n${END}\n`;
    }
  } else {
    body = `# Robin Runbook\n\nOperational symptom/cause/fix entries auto-generated by \`robin doctor --emit-runbook --write\`.\n\n${BEGIN}\n\n${emitRunbookSection(invariants)}\n\n${END}\n`;
  }
  writeFileSync(path, body);
  return { existed };
}
