// store.js — the only writer to events/memos/entities/edges/embeddings.
//
// Spec §5.1. All capture, biographer, dream, ingest, and outbound paths go
// through these primitives. Faculty lenses (knowledge.js, habits.js, …) are
// thin re-exports that bake `kind` in.
//
// Design rules baked in here:
//   1. Embeddings live in separable per-(profile, surface) tables. The store
//      writes the data row and the embedding row in the same transaction.
//   2. Edges use composite-ID UPSERT for idempotence; counter kinds use the
//      `SET field += 1` idiom verified against SurrealDB v3.0.5 (G0.b).
//   3. Content-hash dedupe is opt-in per kind via MEMO_KIND_REGISTRY[kind].dedup_by.
//   4. Subjects + lineage on memos are written as `about` / `derived_from` edges,
//      not as array fields on the memo row. (Spec §5.0 — fields removed.)
//   5. Validation happens via MEMO_KIND_REGISTRY / EDGE_KIND_REGISTRY before
//      any DB write; failures throw with a structured error message.

import { BoundQuery, surql } from 'surrealdb';
import { sha256 } from '../embed/hash.js';
import { activeProfile, embeddingTable } from '../embed/profile-router.js';
import {
  canonicalEndpoints,
  EDGE_KIND_REGISTRY,
  isCounterKind,
  recordStringId,
  validateEdge,
} from './edge-registry.js';
import { MEMO_KIND_REGISTRY, validateAttachment, validateMemoKind } from './kind-registry.js';

// ============================================================================
// WRITE PRIMITIVES
// ============================================================================

/**
 * Capture a raw event into the events firehose.
 *
 * Writes events row + embedding row (in the active profile's events surface)
 * in two queries — one transaction not strictly required because embedding
 * dedupe is keyed on event ID, which is generated by SurrealDB on insert.
 *
 * @returns {{ id, deduped: boolean }}
 */
export async function remember(db, embedder, input) {
  const {
    source,
    content,
    trust = 'trusted',
    scope = 'global',
    tags = [],
    attachments = [],
    meta,
    external_id,
  } = input;
  if (!source) throw new Error('remember: source required');
  if (!content || content.length === 0) throw new Error('remember: content required');

  // Validate attachments (open enum, but known kinds get their shape checked).
  for (const a of attachments) {
    const v = validateAttachment(a);
    if (!v.ok) throw new Error(`remember: attachment invalid: ${v.errors.join('; ')}`);
  }

  const contentHash = sha256(content);

  // Dedupe by content_hash within source — keeps integration syncs idempotent.
  const [existing] = await db
    .query(
      surql`SELECT id FROM events WHERE content_hash = ${contentHash} AND source = ${source} LIMIT 1`,
    )
    .collect();
  if (existing[0]) return { id: existing[0].id, deduped: true };

  // Normalize top-level `external_id` (sync convenience) into meta.external_id
  // — the events schema dropped the top-level column in the redesign.
  const normalizedMeta = external_id != null ? { ...(meta ?? {}), external_id } : meta;

  const fields = {
    source,
    content,
    content_hash: contentHash,
    trust,
    scope,
    tags,
    attachments,
    ...(normalizedMeta ? { meta: normalizedMeta } : {}),
  };
  const [created] = await db.query(surql`CREATE events CONTENT ${fields}`).collect();
  const row = Array.isArray(created) ? created[0] : created;
  const eventId = row.id;

  // Write embedding into the active profile's events surface.
  await writeEmbedding(db, embedder, 'events', eventId, content);

  return { id: eventId, deduped: false };
}

/**
 * Create a memo of any kind. Subjects → `about` edges, lineage → `derived_from`
 * edges, both written via relateAll in the same call site.
 *
 * @returns {{ id, deduped: boolean }}
 */
export async function note(db, embedder, kind, input) {
  if (!kind) throw new Error('note: kind required');
  const v = validateMemoKind(kind, input);
  if (!v.ok) throw new Error(`note(${kind}): ${v.errors.join('; ')}`);
  const {
    content,
    subjects = [],
    confidence,
    scope = 'global',
    tags = [],
    derived_by,
    lineage = [],
    meta = {},
  } = input;

  const spec = MEMO_KIND_REGISTRY[kind];
  const dedupByHash = spec?.dedup_by === 'content_hash';
  const contentHash = sha256(content);

  if (dedupByHash) {
    const [existing] = await db
      .query(
        surql`SELECT id FROM memos WHERE kind = ${kind} AND content_hash = ${contentHash} LIMIT 1`,
      )
      .collect();
    if (existing[0]) return { id: existing[0].id, deduped: true };
  }

  const fields = {
    kind,
    content,
    content_hash: contentHash,
    derived_by,
    scope,
    tags,
    meta,
    ...(confidence !== undefined ? { confidence } : {}),
  };
  const [created] = await db.query(surql`CREATE memos CONTENT ${fields}`).collect();
  const row = Array.isArray(created) ? created[0] : created;
  const memoId = row.id;

  await writeEmbedding(db, embedder, 'memos', memoId, content);

  // Emit `about` edges for subjects (memo → entity).
  if (subjects.length > 0) {
    const rows = subjects.map((s) => ({ from: memoId, to: s, kind: 'about' }));
    await relateAll(db, rows);
  }
  // Emit `derived_from` edges for lineage entries.
  if (lineage.length > 0) {
    const rows = lineage.map((l) => ({ from: memoId, to: l.id ?? l, kind: 'derived_from' }));
    await relateAll(db, rows);
  }

  return { id: memoId, deduped: false };
}

/**
 * Upsert a memo by its `meta.name`. Used by habits today; the primitive is
 * generic (any kind that carries `meta.name`). Increments `signal_count` and
 * refreshes `last_active` on match; creates otherwise.
 *
 * @returns {{ id, signal_increment: 0 | 1 }}
 */
export async function upsertMemoByName(db, embedder, kind, input) {
  const { name } = input;
  if (!name) throw new Error('upsertMemoByName: meta.name required (passed as input.name)');
  const [existing] = await db
    .query(surql`SELECT id FROM memos WHERE kind = ${kind} AND meta.name = ${name} LIMIT 1`)
    .collect();
  if (existing[0]) {
    const id = existing[0].id;
    await db.query(surql`UPDATE ${id} SET signal_count += 1, last_active = time::now()`).collect();
    // Also merge any new lineage as derived_from edges.
    if (input.lineage?.length > 0) {
      const rows = input.lineage.map((l) => ({
        from: id,
        to: l.id ?? l,
        kind: 'derived_from',
      }));
      await relateAll(db, rows);
    }
    return { id, signal_increment: 1 };
  }
  // Create path: ensure `meta.name` is part of the meta we pass through.
  const meta = { ...(input.meta ?? {}), name };
  const result = await note(db, embedder, kind, { ...input, meta });
  return { id: result.id, signal_increment: 0 };
}

/**
 * Relate two records with a typed edge. Registry-validated. Self-loops
 * rejected. Symmetric kinds canonicalize endpoint order. Composite-ID UPSERT
 * for idempotence; counter kinds use `SET weight += 1`.
 */
export async function relate(db, from, to, kind, opts = {}) {
  const v = validateEdge(from, to, kind);
  if (!v.ok) throw new Error(`relate: ${v.errors.join('; ')}`);
  const [cFrom, cTo] = canonicalEndpoints(from, to, kind);
  const counter = isCounterKind(kind);

  // Build a deterministic composite ID. SurrealDB v3 accepts record-as-id-element
  // via the array literal syntax — we use BoundQuery here so the parser sees
  // literal record refs in the ID position.
  const fromIdStr = recordStringId(cFrom);
  const toIdStr = recordStringId(cTo);

  if (counter) {
    const sql = `UPSERT type::record('edges', [$kind, $from, $to]) SET
      kind = $kind, from = $from, to = $to,
      weight += 1,
      last_seen = time::now()`;
    const [ret] = await db
      .query(
        new BoundQuery(sql, {
          kind,
          from: cFrom,
          to: cTo,
        }),
      )
      .collect();
    const row = Array.isArray(ret) ? ret[0] : ret;
    return { id: row?.id };
  }

  const bindings = { kind, from: cFrom, to: cTo };
  const setExprs = ['kind = $kind', 'from = $from', 'to = $to', 'last_seen = time::now()'];
  for (const [field, val] of [
    ['weight', opts.weight],
    ['valid_from', opts.valid_from],
    ['valid_until', opts.valid_until],
    ['context', opts.context],
    ['meta', opts.meta],
  ]) {
    if (val !== undefined && val !== null) {
      bindings[field] = val;
      setExprs.push(`${field} = $${field}`);
    }
  }
  const sql = `UPSERT type::record('edges', [$kind, $from, $to]) SET ${setExprs.join(', ')}`;
  const [ret] = await db.query(new BoundQuery(sql, bindings)).collect();
  const row = Array.isArray(ret) ? ret[0] : ret;
  return { id: row?.id, fromId: fromIdStr, toId: toIdStr };
}

/**
 * Bulk relate. Same semantics as `relate` but batched into one statement —
 * used by biographer to emit 8-20 edges per processed event.
 */
export async function relateAll(db, rows) {
  if (!Array.isArray(rows) || rows.length === 0) return { ids: [] };
  const ids = [];
  // SurrealDB doesn't have a multi-row UPSERT primitive for arbitrary IDs;
  // batch into one BEGIN/COMMIT block for atomicity.
  for (const row of rows) {
    const { id } = await relate(db, row.from, row.to, row.kind, row);
    ids.push(id);
  }
  return { ids };
}

/**
 * Add a `supersedes` edge new_memo → old_memo. fn::freshness will return 0
 * for old_memo from now on (per its inbound supersedes check). The old memo
 * row is NOT updated/deleted — historical readings remain queryable.
 */
export async function supersede(db, oldId, newId) {
  const { id } = await relate(db, newId, oldId, 'supersedes');
  return { superseded: oldId, by: newId, edge: id };
}

/**
 * Mark two memos as contradicting each other (symmetric, both visible).
 */
export async function flagContradiction(db, idA, idB, opts = {}) {
  return relate(db, idA, idB, 'contradicts', opts);
}

/**
 * Update a memo's `meta` field by merging in a patch. Used by foresight to
 * record prediction resolution (resolved_at / correct / actual_outcome).
 */
export async function updateMemoMeta(db, id, patch) {
  await db.query(surql`UPDATE ${id} MERGE { meta: ${patch} }`).collect();
}

// ============================================================================
// EMBEDDINGS
// ============================================================================

/**
 * Write the embedding for a record into the active profile's embedding table
 * for the given surface. Idempotent (UPSERT by the record's ID).
 *
 * Profile name is read from `runtime:embedder.active_profile` and validated
 * against /^[a-z0-9-]+$/ in profile-router; surface against /^events|memos|entities$/.
 * Table name is therefore safe to interpolate.
 */
async function writeEmbedding(db, embedder, surface, recordId, text) {
  const profile = await activeProfile(db);
  const table = embeddingTable(profile, surface);
  const vec = Array.from(await embedder.embed(text));
  const sql = 'UPSERT type::record($tb, [$rec]) SET record = $rec, vector = $vec, ts = time::now()';
  await db
    .query(
      new BoundQuery(sql, {
        tb: table,
        rec: recordId,
        vec,
      }),
    )
    .collect();
}

// ============================================================================
// READ PRIMITIVES
// ============================================================================

/**
 * Read a memo with hydrated subjects, lineage, contradictions count.
 */
export async function getMemo(db, id) {
  const [rows] = await db
    .query(surql`SELECT *, fn::freshness(id) AS freshness FROM ${id}`)
    .collect();
  const memo = rows[0];
  if (!memo) return null;
  const [subjects] = await db
    .query(surql`SELECT VALUE to FROM edges WHERE kind = 'about' AND from = ${id}`)
    .collect();
  const [lineage] = await db
    .query(surql`SELECT VALUE to FROM edges WHERE kind = 'derived_from' AND from = ${id}`)
    .collect();
  const [contraRows] = await db
    .query(
      surql`SELECT count() AS n FROM edges WHERE kind = 'contradicts' AND (from = ${id} OR to = ${id}) GROUP ALL`,
    )
    .collect();
  return {
    ...memo,
    subjects,
    lineage,
    contradictions: contraRows?.[0]?.n ?? 0,
  };
}

/**
 * HNSW kNN over memos. Filters by kind / scope(s) / tags / since are applied
 * during the SQL query (indexed where applicable). Default excludes ephemeral
 * scopes; pass `scopes: ['*']` to include everything.
 *
 * Returns `{ hits: [{ record, distance, ... }] }` — caller layers rank.score.
 */
export async function searchMemos(db, embedder, query, opts = {}) {
  return _surfaceSearch(db, embedder, 'memos', query, opts);
}

export async function searchEvents(db, embedder, query, opts = {}) {
  return _surfaceSearch(db, embedder, 'events', query, opts);
}

export async function searchEntities(db, embedder, query, opts = {}) {
  return _surfaceSearch(db, embedder, 'entities', query, opts);
}

async function _surfaceSearch(db, embedder, surface, query, opts) {
  const limit = Number.isInteger(opts.limit) ? opts.limit : 10;
  if (limit < 1 || limit > 100) {
    throw new Error(`searchMemos: limit out of range [1,100]: ${limit}`);
  }
  const ef = Math.max(64, limit * 8);
  const _profile = (await import('../embed/profile-router.js')).then; // tree-shake guard
  const { readProfile } = await import('../embed/profile-router.js');
  const readProf = await readProfile(db);
  const embeddingTbl = embeddingTable(readProf, surface);
  const qvec = Array.from(await embedder.embed(query));

  // Step 1: HNSW kNN on the per-surface embeddings table.
  // TIMEOUT 2s is defensive — bounds runaway HNSW exploration if the index
  // is in a pathological state. Recall is fail-soft from the hook side, so
  // a timeout produces an empty hit list rather than crashing the turn.
  const knnSql = `SELECT record, vector::distance::knn() AS dist
                  FROM ${embeddingTbl}
                  WHERE vector <|${limit}, ${ef}|> $qvec
                  ORDER BY dist
                  LIMIT ${limit}
                  TIMEOUT 2s`;
  const [knnRows] = await db.query(new BoundQuery(knnSql, { qvec })).collect();
  if (knnRows.length === 0) return { hits: [] };

  // Step 2: fetch records and apply scope/kind/tags filter.
  const ids = knnRows.map((r) => r.record);
  const idDist = new Map(knnRows.map((r) => [recordStringId(r.record), r.dist]));

  const filters = ['id IN $ids'];
  const bindings = { ids };
  if (surface === 'memos' && opts.kind) {
    bindings.kind = opts.kind;
    filters.push('kind = $kind');
  }
  if (surface === 'events' && opts.source) {
    bindings.source = opts.source;
    filters.push('source = $source');
  }
  if (surface === 'entities' && opts.type) {
    bindings.entitytype = opts.type;
    filters.push('type = $entitytype');
  }
  const scopes = opts.scopes;
  if (scopes === undefined && !opts.includeEphemeral) {
    // default: exclude ephemerals
    filters.push(
      `(scope = 'global' OR string::starts_with(scope, 'project:') OR string::starts_with(scope, 'integration:') OR scope = 'private')`,
    );
  } else if (Array.isArray(scopes) && !scopes.includes('*')) {
    bindings.scopes = scopes;
    filters.push('scope IN $scopes');
  }
  if (opts.tags && opts.tags.length > 0) {
    bindings.tags = opts.tags;
    filters.push('tags CONTAINSANY $tags');
  }
  if (opts.since) {
    bindings.since = new Date(opts.since);
    const tsField = surface === 'events' ? 'ts' : 'derived_at';
    filters.push(`${tsField} >= $since`);
  }

  const fetchSql = `SELECT * FROM ${surface} WHERE ${filters.join(' AND ')}`;
  const [rows] = await db.query(new BoundQuery(fetchSql, bindings)).collect();

  const hits = rows
    .map((row) => ({ record: row, distance: idDist.get(recordStringId(row.id)) ?? 1 }))
    .sort((a, b) => a.distance - b.distance);

  return { hits };
}

/**
 * Non-vector list (index-backed): used by lenses for chronological views.
 */
export async function listMemos(db, opts = {}) {
  const { kind, scope, since, until, limit = 50 } = opts;
  if (!Number.isInteger(limit) || limit < 1 || limit > 1000) {
    throw new Error(`listMemos: limit out of range [1,1000]: ${limit}`);
  }
  const filters = [];
  const bindings = {};
  if (kind) {
    filters.push('kind = $kind');
    bindings.kind = kind;
  }
  if (scope) {
    filters.push('scope = $scope');
    bindings.scope = scope;
  }
  if (since) {
    filters.push('derived_at >= $since');
    bindings.since = new Date(since);
  }
  if (until) {
    filters.push('derived_at <= $until');
    bindings.until = new Date(until);
  }
  const where = filters.length > 0 ? `WHERE ${filters.join(' AND ')}` : '';
  const sql = `SELECT * FROM memos ${where} ORDER BY last_active DESC LIMIT ${limit}`;
  const [rows] = await db.query(new BoundQuery(sql, bindings)).collect();
  return rows;
}

/**
 * Bidirectional neighbor lookup along an edge kind.
 * For symmetric kinds, returns the *other* endpoint regardless of direction.
 * For asymmetric kinds with `direction = 'out'` (default), returns `to`s of
 * outbound edges; `direction = 'in'` returns `from`s of inbound; `'both'`
 * returns the union.
 */
export async function neighbors(db, recordId, kind, opts = {}) {
  const { limit = 10, direction = 'out' } = opts;
  if (!Number.isInteger(limit) || limit < 1 || limit > 1000) {
    throw new Error(`neighbors: limit out of range [1,1000]: ${limit}`);
  }
  const spec = EDGE_KIND_REGISTRY[kind];
  if (!spec) throw new Error(`neighbors: unknown kind ${kind}`);
  let whereClause;
  if (spec.symmetric) {
    whereClause = '(from = $e OR to = $e)';
  } else if (direction === 'out') {
    whereClause = 'from = $e';
  } else if (direction === 'in') {
    whereClause = 'to = $e';
  } else {
    whereClause = '(from = $e OR to = $e)';
  }
  const sql = `SELECT
    IF from = $e THEN to ELSE from END AS other,
    weight, last_seen, valid_from, valid_until
    FROM edges
    WHERE kind = $k AND ${whereClause}
    ORDER BY weight DESC
    LIMIT ${limit}`;
  const [rows] = await db.query(new BoundQuery(sql, { e: recordId, k: kind })).collect();
  return rows;
}

// ============================================================================
// ENTITY UPSERT (delegates to existing 3-stage cascade for now)
// ============================================================================

/**
 * Upsert an entity by name (exact + embedding + LLM disambig cascade).
 * Current implementation delegates to the existing 3-stage cascade in
 * src/graph/stage*.js; this primitive exists so all writes route through
 * one module. The embedding write moves to the per-surface entities table.
 */
export async function upsertEntity(db, embedder, input) {
  const { upsertEntityCascade } = await import('../graph/upsert-entity.js');
  const result = await upsertEntityCascade(db, embedder, input);
  // Write embedding into the active profile's entities surface.
  if (result.id && result.embedding_source) {
    await writeEmbedding(db, embedder, 'entities', result.id, result.embedding_source);
  }
  return result;
}
