// Runbook generator. Walks the registry in phase order and emits one
// markdown block per invariant via its explain() function. Used by
// `robin doctor --emit-runbook` and the CI/precommit drift guards.

import { PHASES } from './policy.js';
import { phaseOrdered } from './index.js';

export const SENTINEL_BEGIN = '<!-- robin:runbook:begin -->';
export const SENTINEL_END = '<!-- robin:runbook:end -->';

const PHASE_TITLES = {
  paths: 'Paths',
  db: 'Database',
  mcp: 'MCP wiring',
  integrations: 'Integrations',
  runtime: 'Runtime',
  meta: 'Meta',
};

/**
 * Render the runbook markdown block (NOT including the sentinel comments).
 * Ordered by PHASES, then registry-order within each phase.
 */
export function renderRunbook(invariants = phaseOrdered()) {
  const grouped = new Map(PHASES.map((p) => [p, []]));
  for (const inv of invariants) {
    grouped.get(inv.phase)?.push(inv);
  }

  const sections = [];
  sections.push('## Operational invariants (auto-generated)');
  sections.push('');
  sections.push('> This section is regenerated by `robin doctor --emit-runbook --write`. Do not edit between the sentinel comments — your edits will be overwritten.');
  sections.push('');

  for (const phase of PHASES) {
    const entries = grouped.get(phase);
    if (!entries || entries.length === 0) continue;
    sections.push(`### ${PHASE_TITLES[phase] ?? phase} (\`${phase}\`)`);
    sections.push('');
    for (const inv of entries) {
      sections.push(inv.explain());
      sections.push('');
    }
  }
  return sections.join('\n').trim();
}

/**
 * Replace the sentinel-bracketed block in `existing` markdown with the
 * generated runbook. If sentinels are missing, returns existing + appended
 * block (with sentinels) at the end.
 */
export function replaceSentinelBlock(existing, generatedBody) {
  const wrapped = `${SENTINEL_BEGIN}\n\n${generatedBody}\n\n${SENTINEL_END}`;
  const beginIdx = existing.indexOf(SENTINEL_BEGIN);
  const endIdx = existing.indexOf(SENTINEL_END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    const sep = existing.endsWith('\n') ? '\n' : '\n\n';
    return existing + sep + wrapped + '\n';
  }
  const before = existing.slice(0, beginIdx);
  const after = existing.slice(endIdx + SENTINEL_END.length);
  return before + wrapped + after;
}

/**
 * Returns true if existing markdown already contains the generated block
 * verbatim (byte-identical between sentinels).
 */
export function isInSync(existing, generatedBody) {
  const beginIdx = existing.indexOf(SENTINEL_BEGIN);
  const endIdx = existing.indexOf(SENTINEL_END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) return false;
  const between = existing.slice(beginIdx + SENTINEL_BEGIN.length, endIdx).trim();
  return between === generatedBody.trim();
}
